# Generated by Django 3.1.5 on 2021-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210126_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
