# Generated by Django 3.1.5 on 2021-01-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210126_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='codigo_cinta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cinta'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='codigo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='codigo_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursal'),
        ),
    ]
