# Generated by Django 3.1.5 on 2021-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210126_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(),
        ),
    ]
